from django.contrib import admin
from .models import Assumptions,Absenteeis_and_Defective,Cost_Assumptions,Salary_growth_and_Incentives,Financial,Depreciation_Schedule_For_Balance_Sheet_Straight_Line,Clearing_and_Forwarding_Exports,Working_capital_ratios_and_assumtpions,Preliminary_and_Preoperative_expenses,Number_of_Lines,Assumptions_for_Production_Calculations,Machinery_Growth_Figures,No_of_Operators_per_line_as_per_Operation_Bulletin,Number_of_machines_planned,Productivity_Build_Up_for_New_Capactites_Year1,Productivity_Build_Up_for_New_Capactites_Year2,Productivity_Build_Up_for_New_Capactites_Year3,Summary_year1,Summary_year2,Summary_year3
# class AssumptionsAdmin(admin.ModelAdmin):
#     prepopulated_fields = {"slug": ('self.slug',)}

admin.site.register(Assumptions)
admin.site.register(Absenteeis_and_Defective)
admin.site.register(Cost_Assumptions)
admin.site.register(Salary_growth_and_Incentives)
admin.site.register(Financial)
admin.site.register(Depreciation_Schedule_For_Balance_Sheet_Straight_Line)
admin.site.register(Clearing_and_Forwarding_Exports)
admin.site.register(Working_capital_ratios_and_assumtpions)
admin.site.register(Preliminary_and_Preoperative_expenses)
admin.site.register(Number_of_Lines)
admin.site.register(Assumptions_for_Production_Calculations)
admin.site.register(Machinery_Growth_Figures)
admin.site.register(No_of_Operators_per_line_as_per_Operation_Bulletin)
admin.site.register(Number_of_machines_planned)
admin.site.register(Productivity_Build_Up_for_New_Capactites_Year1)
admin.site.register(Productivity_Build_Up_for_New_Capactites_Year2)
admin.site.register(Productivity_Build_Up_for_New_Capactites_Year3)
admin.site.register(Summary_year1)
admin.site.register(Summary_year2)
admin.site.register(Summary_year3)


