# Generated by Django 3.1.6 on 2021-02-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assumptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_working_hrs_per_day', models.IntegerField()),
                ('Attendance_Time_hrs_perday', models.IntegerField()),
                ('Working_minutes_per_day', models.IntegerField()),
                ('No_of_working_days_per_month', models.IntegerField()),
                ('Total_no_of_production_days_per_year', models.IntegerField()),
                ('No_of_shifts_per_day', models.IntegerField()),
                ('Exchange_rate', models.IntegerField()),
            ],
        ),
    ]
