# Generated by Django 3.1.6 on 2021-02-15 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year1', models.CharField(max_length=25)),
                ('Year2', models.CharField(max_length=25)),
                ('Year3', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Absenteeis_and_Defective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sewing', models.CharField(max_length=25)),
                ('Cutting', models.CharField(max_length=25)),
                ('Finishing', models.CharField(max_length=25)),
                ('Cutting_Output_as_percentage_of_Sewing_Output', models.CharField(max_length=25)),
                ('Finishing_Output_as_percentage_of_Sewing_Output', models.CharField(max_length=25)),
                ('Extra_Sewing_Machines_Required', models.CharField(max_length=25)),
                ('Cutting_Loss', models.CharField(max_length=25)),
                ('Defective_Goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assumptions.year')),
            ],
        ),
    ]
