# Generated by Django 3.1.6 on 2021-02-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0003_auto_20210215_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year1', models.CharField(max_length=25)),
                ('Year2', models.CharField(max_length=25)),
                ('Year3', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='absenteeis_and_defective',
            name='Defective_Goods',
        ),
    ]
