# Generated by Django 3.1.6 on 2021-02-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0004_auto_20210215_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost_Assumptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=25, verbose_name='Electricity cost per KW-Hr (INR.)')),
                ('b', models.CharField(max_length=250, verbose_name='Electricity requirement for light & fans (Kw-Hr per 1000 Sq Ft.)')),
                ('c', models.CharField(max_length=25, verbose_name='Water consumption per person per day (Lts.)')),
                ('d', models.CharField(max_length=25, verbose_name='Water Cost (INR. Per 1000 Lts.)')),
                ('e', models.CharField(max_length=25, verbose_name='Construction cost per sq ft. (INR.)')),
                ('f', models.CharField(max_length=25, verbose_name='Land Cost (INR per Acre)')),
                ('g', models.CharField(max_length=25, verbose_name='TotalBuilt up area area (Acres)')),
                ('h', models.CharField(max_length=25, verbose_name='Total land as % of covered area')),
                ('i', models.CharField(max_length=25, verbose_name='Land development cost (INR /Acre)')),
                ('j', models.CharField(max_length=25, verbose_name='Office area (Sq ft)')),
                ('k', models.CharField(max_length=25, verbose_name='Office development cost (INR./sq ft)')),
                ('l', models.CharField(max_length=25, verbose_name='False ceiling cost (INR. Per sq ft)')),
                ('m', models.CharField(max_length=25, verbose_name='Road construction cost (INR./sq ft.)')),
                ('n', models.CharField(max_length=25, verbose_name='ETP cost')),
                ('o', models.CharField(max_length=25, verbose_name='STP cost')),
                ('p', models.CharField(max_length=25, verbose_name='Generator cost (100KW)')),
                ('q', models.CharField(max_length=25, verbose_name='Generator cost (150KW)')),
                ('r', models.CharField(max_length=25, verbose_name='Electrical expenses (INR)')),
                ('s', models.CharField(max_length=25, verbose_name='Product Development Expenses (% of Total sales)')),
                ('t', models.CharField(max_length=25, verbose_name='Miscllaneous fixed asset per sewing machine (INR.)')),
                ('u', models.CharField(max_length=25, verbose_name='Cutting')),
                ('v', models.CharField(max_length=25, verbose_name='Provision for contingency')),
            ],
        ),
        migrations.AddField(
            model_name='year',
            name='absdef',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assumptions.absenteeis_and_defective'),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='Attendance_Time_hrs_perday',
            field=models.IntegerField(verbose_name='Attendance Time (hrs per day)'),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='No_of_shifts_per_day',
            field=models.IntegerField(verbose_name='No. of shifts per day'),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='No_of_working_days_per_month',
            field=models.IntegerField(verbose_name='No. of working days per month'),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='No_of_working_hrs_per_day',
            field=models.IntegerField(verbose_name='No. of working hrs. per day'),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='Total_no_of_production_days_per_year',
            field=models.IntegerField(verbose_name='Total no of production days per year'),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='Working_minutes_per_day',
            field=models.IntegerField(verbose_name='Working minutes per day'),
        ),
    ]
