# Generated by Django 3.1.6 on 2021-02-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0005_auto_20210215_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='absdef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assumptions.absenteeis_and_defective'),
        ),
    ]
