# Generated by Django 3.1.6 on 2021-02-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0006_auto_20210215_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=25, verbose_name='Ratio D/E')),
                ('b', models.CharField(max_length=25, verbose_name='Interest on Term Loan  Y1 & Y2')),
                ('c', models.CharField(max_length=25, verbose_name='Interest on Term Loan  Y3 onwards')),
                ('d', models.CharField(max_length=25, verbose_name='Interest on Working Capital Financing')),
                ('e', models.CharField(max_length=25, verbose_name='Interest Income on Cash Surplus')),
                ('f', models.CharField(max_length=25, verbose_name='Tax')),
                ('g', models.CharField(max_length=25, verbose_name='Business Commissions on Sales Value (For 1st 3 yrs)')),
                ('h', models.CharField(max_length=25, verbose_name='Duty Draw Backs')),
            ],
        ),
        migrations.CreateModel(
            name='Salary_growth_and_Incentives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=25, verbose_name='Salary Growth % year on year')),
                ('b', models.CharField(max_length=25, verbose_name='Wages Growth % year on year')),
                ('c', models.CharField(max_length=25, verbose_name='Incentive % per annum')),
            ],
        ),
    ]
