# Generated by Django 3.1.6 on 2021-02-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0007_financial_salary_growth_and_incentives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financial',
            old_name='a',
            new_name='aa',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='b',
            new_name='bb',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='c',
            new_name='cc',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='d',
            new_name='dd',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='e',
            new_name='ee',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='f',
            new_name='ff',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='g',
            new_name='gg',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='h',
            new_name='hh',
        ),
        migrations.RenameField(
            model_name='salary_growth_and_incentives',
            old_name='c',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='salary_growth_and_incentives',
            old_name='b',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='salary_growth_and_incentives',
            old_name='a',
            new_name='z',
        ),
    ]
