# Generated by Django 3.1.6 on 2021-02-16 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0008_auto_20210215_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='absdef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assumptions.absenteeis_and_defective'),
        ),
    ]
