# Generated by Django 3.1.6 on 2021-02-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0009_auto_20210216_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='absdef',
            field=models.ForeignKey(blank=True, db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='assumptions.absenteeis_and_defective'),
        ),
    ]
