# Generated by Django 3.1.6 on 2021-02-16 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0010_auto_20210216_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='absdef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assumptions.absenteeis_and_defective'),
        ),
    ]
