# Generated by Django 3.1.6 on 2021-02-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0011_auto_20210216_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='absenteeis_and_defective',
            name='Year1',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absenteeis_and_defective',
            name='Year2',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absenteeis_and_defective',
            name='Year3',
            field=models.CharField(default=21, max_length=25),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
