# Generated by Django 3.1.6 on 2021-02-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0012_auto_20210216_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financial',
            old_name='aa',
            new_name='a',
        ),
    ]
