# Generated by Django 3.1.6 on 2021-02-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0013_auto_20210216_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financial',
            old_name='bb',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='cc',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='dd',
            new_name='d',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='ee',
            new_name='e',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='ff',
            new_name='f',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='gg',
            new_name='g',
        ),
        migrations.RenameField(
            model_name='financial',
            old_name='hh',
            new_name='h',
        ),
    ]
