# Generated by Django 3.1.6 on 2021-02-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0014_auto_20210216_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='assumptions',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
