# Generated by Django 3.1.6 on 2021-02-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0015_assumptions_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assumptions',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
