# Generated by Django 3.1.6 on 2021-02-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0016_auto_20210225_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assumptions',
            name='slug',
            field=models.CharField(default='No_of_working_hrs_per_day', max_length=25),
        ),
    ]
