# Generated by Django 3.1.6 on 2021-02-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0018_auto_20210225_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assumptions',
            name='No_of_working_hrs_per_day',
        ),
        migrations.RemoveField(
            model_name='assumptions',
            name='slug',
        ),
    ]
