# Generated by Django 3.1.6 on 2021-02-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0019_auto_20210225_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='assumptions',
            name='No_of_working_hrs_per_day',
            field=models.IntegerField(default=None, verbose_name='No. of working hrs. per day'),
        ),
        migrations.AddField(
            model_name='assumptions',
            name='slug',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
