# Generated by Django 3.1.6 on 2021-02-26 05:06

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0020_auto_20210225_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assumptions',
            name='No_of_working_hrs_per_day',
            field=models.IntegerField(default=123, verbose_name='No. of working hrs. per day'),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='slug',
            field=autoslug.fields.AutoSlugField(),
        ),
    ]
