# Generated by Django 3.1.6 on 2021-02-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0021_auto_20210226_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assumptions',
            name='No_of_working_hrs_per_day',
            field=models.IntegerField(verbose_name='No. of working hrs. per day'),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='Working_minutes_per_day',
            field=models.IntegerField(default=models.IntegerField(verbose_name='No. of working hrs. per day'), verbose_name='Working minutes per day'),
        ),
    ]
