# Generated by Django 3.1.6 on 2021-03-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0022_auto_20210226_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assumptions',
            name='slug',
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='Working_minutes_per_day',
            field=models.IntegerField(verbose_name='Working minutes per day'),
        ),
    ]
