# Generated by Django 3.1.6 on 2021-03-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0023_auto_20210301_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenteeis_and_defective',
            name='Year1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='absenteeis_and_defective',
            name='Year2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='absenteeis_and_defective',
            name='Year3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
