# Generated by Django 3.1.6 on 2021-03-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0025_auto_20210301_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenteeis_and_defective',
            name='Cutting',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='absenteeis_and_defective',
            name='Cutting_Loss',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='absenteeis_and_defective',
            name='Cutting_Output_as_percentage_of_Sewing_Output',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='absenteeis_and_defective',
            name='Extra_Sewing_Machines_Required',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='absenteeis_and_defective',
            name='Finishing',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='absenteeis_and_defective',
            name='Finishing_Output_as_percentage_of_Sewing_Output',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='absenteeis_and_defective',
            name='Sewing',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='No_of_shifts_per_day',
            field=models.IntegerField(null=True, verbose_name='No. of shifts per day'),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='No_of_working_days_per_month',
            field=models.IntegerField(null=True, verbose_name='No. of working days per month'),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='No_of_working_hrs_per_day',
            field=models.IntegerField(null=True, verbose_name='No. of working hrs. per day'),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='Total_no_of_production_days_per_year',
            field=models.IntegerField(null=True, verbose_name='Total no of production days per year'),
        ),
        migrations.AlterField(
            model_name='assumptions',
            name='Working_minutes_per_day',
            field=models.IntegerField(null=True, verbose_name='Working minutes per day'),
        ),
    ]
