# Generated by Django 3.1.6 on 2021-03-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0030_auto_20210301_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_assumptions',
            name='a',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Electricity cost per KW-Hr (INR.)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='b',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Electricity requirement for light & fans (Kw-Hr per 1000 Sq Ft.)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='c',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Water consumption per person per day (Lts.)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='d',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Water Cost (INR. Per 1000 Lts.)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='e',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Construction cost per sq ft. (INR.)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='f',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Land Cost (INR per Acre)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='g',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='TotalBuilt up area area (Acres)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='h',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Total land as % of covered area'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='i',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Land development cost (INR /Acre)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='j',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Office area (Sq ft)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='k',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Office development cost (INR./sq ft)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='l',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='False ceiling cost (INR. Per sq ft)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='m',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Road construction cost (INR./sq ft.)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='n',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ETP cost'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='o',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='STP cost'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='p',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Generator cost (100KW)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='q',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Generator cost (150KW)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='r',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Electrical expenses (INR)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='s',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Product Development Expenses (% of Total sales)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='t',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Miscllaneous fixed asset per sewing machine (INR.)'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='u',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Cutting'),
        ),
        migrations.AlterField(
            model_name='cost_assumptions',
            name='v',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Provision for contingency'),
        ),
    ]
