# Generated by Django 3.1.6 on 2021-03-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0031_auto_20210301_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='assumptions',
            name='No_of_years',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. of years'),
        ),
    ]
