# Generated by Django 3.1.6 on 2021-03-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0032_assumptions_no_of_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assumptions',
            name='No_of_years',
            field=models.IntegerField(blank=True, default=0, verbose_name='No. of years'),
        ),
    ]
