# Generated by Django 3.1.6 on 2021-03-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0033_auto_20210302_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_assumptions',
            name='t',
            field=models.CharField(blank=True, default=1000, max_length=25, verbose_name='Miscllaneous fixed asset per sewing machine (INR.)'),
        ),
    ]
