# Generated by Django 3.1.6 on 2021-03-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0034_auto_20210302_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assumptions',
            name='Exchange_rate',
            field=models.IntegerField(default=0),
        ),
    ]
