# Generated by Django 3.1.7 on 2021-03-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0036_auto_20210302_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearing_and_Forwarding_Exports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(blank=True, max_length=25, null=True, verbose_name='For Exports')),
                ('b', models.CharField(blank=True, max_length=25, null=True, verbose_name='Average pieces per container')),
                ('c', models.CharField(blank=True, max_length=25, null=True, verbose_name='Port Handling charges (INR. per container) - all incl')),
                ('d', models.CharField(blank=True, max_length=25, null=True, verbose_name='Transportation (in INR./ container)')),
                ('e', models.CharField(blank=True, max_length=25, null=True, verbose_name='Material Handling @')),
                ('f', models.CharField(blank=True, max_length=25, null=True, verbose_name='Duty - Manual Machines')),
                ('g', models.CharField(blank=True, max_length=25, null=True, verbose_name='Duty - Electronic machines')),
            ],
        ),
        migrations.CreateModel(
            name='Depreciation_Schedule_For_Balance_Sheet_Straight_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(blank=True, max_length=25, null=True, verbose_name='Factory Building ')),
                ('b', models.CharField(blank=True, max_length=25, null=True, verbose_name='Plant & Machinery')),
                ('c', models.CharField(blank=True, max_length=25, null=True, verbose_name='IT')),
                ('d', models.CharField(blank=True, max_length=25, null=True, verbose_name='Misc Fixed Assets')),
                ('e', models.CharField(blank=True, max_length=25, null=True, verbose_name='Amortisation of Pre Operative Expenses')),
            ],
        ),
        migrations.AlterField(
            model_name='financial',
            name='a',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Ratio D/E'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='b',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Interest on Term Loan  Y1 & Y2'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='c',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Interest on Term Loan  Y3 onwards'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='d',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Interest on Working Capital Financing'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='e',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Interest Income on Cash Surplus'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='f',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='g',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Business Commissions on Sales Value (For 1st 3 yrs)'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='h',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Duty Draw Backs'),
        ),
        migrations.AlterField(
            model_name='salary_growth_and_incentives',
            name='x',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Incentive % per annum'),
        ),
        migrations.AlterField(
            model_name='salary_growth_and_incentives',
            name='y',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Wages Growth % year on year'),
        ),
        migrations.AlterField(
            model_name='salary_growth_and_incentives',
            name='z',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Salary Growth % year on year'),
        ),
    ]
