# Generated by Django 3.1.7 on 2021-03-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacityrevenue', '0002_auto_20210307_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity_revenue_table',
            name='no_of_years',
            field=models.IntegerField(default=0),
        ),
    ]
