# Generated by Django 3.1.7 on 2021-03-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacityrevenue', '0004_auto_20210307_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity_revenue_table',
            name='output_100per',
            field=models.FloatField(default=0),
        ),
    ]
