# Generated by Django 3.1.7 on 2021-03-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacityrevenue', '0005_capacity_revenue_table_output_100per'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacity_revenue_table',
            name='total_sewing_sams',
            field=models.FloatField(default=0),
        ),
    ]
