# Generated by Django 3.1.7 on 2021-03-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacityrevenue', '0008_auto_20210308_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity_revenue_table',
            name='total_sams',
            field=models.FloatField(default=76.05),
        ),
    ]
